### ISSUE TITLE
Catalog Import fails on step 4: Removing Brands

### ISSUE THREAD

**Issue by MoosMase** [bigcommerce/bigcommerce-for-wordpress#324]
**Expected Behavior**
utvaudio.com is able to import/sync catalog without issue

**Actual Behavior** 
Sync fails at step 4: Removing Brands

Plug-in logs show that the $name field exceeds the 50 character limit:
`[2021-12-28 17:07:00] BigCommerce.INFO: Starting import [] []
[2021-12-28 17:07:01] BigCommerce.INFO: Running import task {"state":"started","description":"Fetching store information"} []
[2021-12-28 17:07:01] BigCommerce.DEBUG: Requesting store settings [] []
[2021-12-28 17:07:02] BigCommerce.DEBUG: Retrieved store settings {"settings":{"bigcommerce_domain":"creativeaudio.net","bigcommerce_currency_code":"USD","bigcommerce_currency_symbol":"$","bigcommerce_currency_symbol_position":"left","bigcommerce_decimal_units":2,"bigcommerce_integer_units":4,"bigcommerce_mass_unit":"lb","bigcommerce_length_unit":"in","bigcommerce_wishlists_enabled":1,"bigcommerce_facebook_pixel_id":"973457486100126","bigcommerce_google_analytics_id":"UA-806506-8"}} []
[2021-12-28 17:07:04] BigCommerce.INFO: Running import task {"state":"fetched_store","description":"Retrieving currency settings"} []
[2021-12-28 17:07:04] BigCommerce.DEBUG: Requesting currency settings [] []
[2021-12-28 17:07:05] BigCommerce.INFO: Running import task {"state":"fetched_currencies","description":"Removing Categories"} []
[2021-12-28 17:07:05] BigCommerce.DEBUG: Removing deleted terms for bigcommerce_category taxonomy {"page":1,"limit":50,"taxonomy":"bigcommerce_category"} []
[2021-12-28 17:07:05] BigCommerce.DEBUG: bigcommerce_category purge ready for next page of terms {"next":2,"taxonomy":"bigcommerce_category"} []
[2021-12-28 17:07:07] BigCommerce.INFO: Running import task {"state":"purging_categories","description":"Removing Categories"} []
[2021-12-28 17:07:07] BigCommerce.DEBUG: Removing deleted terms for bigcommerce_category taxonomy {"page":2,"limit":50,"taxonomy":"bigcommerce_category"} []
[2021-12-28 17:07:07] BigCommerce.DEBUG: bigcommerce_category purge ready for next page of terms {"next":3,"taxonomy":"bigcommerce_category"} []
[2021-12-28 17:07:08] BigCommerce.INFO: Running import task {"state":"purging_categories","description":"Removing Categories"} []
[2021-12-28 17:07:08] BigCommerce.DEBUG: Removing deleted terms for bigcommerce_category taxonomy {"page":3,"limit":50,"taxonomy":"bigcommerce_category"} []
[2021-12-28 17:07:08] BigCommerce.DEBUG: bigcommerce_category purge ready for next page of terms {"next":4,"taxonomy":"bigcommerce_category"} []
[2021-12-28 17:07:10] BigCommerce.INFO: Running import task {"state":"purging_categories","description":"Removing Categories"} []
[2021-12-28 17:07:10] BigCommerce.DEBUG: Removing deleted terms for bigcommerce_category taxonomy {"page":4,"limit":50,"taxonomy":"bigcommerce_category"} []
[2021-12-28 17:07:11] BigCommerce.DEBUG: bigcommerce_category purge ready for next page of terms {"next":5,"taxonomy":"bigcommerce_category"} []
[2021-12-28 17:07:11] BigCommerce.INFO: Running import task {"state":"purging_categories","description":"Removing Categories"} []
[2021-12-28 17:07:11] BigCommerce.DEBUG: Removing deleted terms for bigcommerce_category taxonomy {"page":5,"limit":50,"taxonomy":"bigcommerce_category"} []
[2021-12-28 17:07:14] BigCommerce.INFO: Running import task {"state":"purged_categories","description":"Removing Brands"} []
[2021-12-28 17:07:14] BigCommerce.DEBUG: Removing deleted terms for bigcommerce_brand taxonomy {"page":1,"limit":50,"taxonomy":"bigcommerce_brand"} []
[2021-12-28 17:07:14] BigCommerce.INFO: Running import task {"state":"purged_brands","description":"Updating Categories"} []
[2021-12-28 17:07:14] BigCommerce.DEBUG: Importing terms for bigcommerce_category taxonomy {"page":49,"limit":5,"taxonomy":"bigcommerce_category"} []
[2021-12-28 17:07:14] BigCommerce.ERROR: invalid length for $name when calling Category., must be smaller than or equal to 50. [] []
[2021-12-28 17:07:14] BigCommerce.DEBUG: #0 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/vendor/moderntribe/bigcommerce-api-php-v3/src/ObjectSerializer.php(291): BigCommerce\Api\v3\Model\Category->setName('Chevrolet and G...') #1 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/vendor/moderntribe/bigcommerce-api-php-v3/src/ObjectSerializer.php(236): BigCommerce\Api\v3\ObjectSerializer::deserialize(Object(stdClass), '\\BigCommerce\\Ap...', NULL) #2 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/vendor/moderntribe/bigcommerce-api-php-v3/src/ObjectSerializer.php(291): BigCommerce\Api\v3\ObjectSerializer::deserialize(Array, '\\BigCommerce\\Ap...', NULL) #3 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/vendor/moderntribe/bigcommerce-api-php-v3/src/Api/CatalogApi.php(6471): BigCommerce\Api\v3\ObjectSerializer::deserialize(Object(stdClass), '\\BigCommerce\\Ap...', Array) #4 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/vendor/moderntribe/bigcommerce-api-php-v3/src/Api/CatalogApi.php(6415): BigCommerce\Api\v3\Api\CatalogApi->getCategoriesWithHttpInfo(Array) #5 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/src/BigCommerce/Import/Processors/Category_Import.php(32): BigCommerce\Api\v3\Api\CatalogApi->getCategories(Array) #6 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/src/BigCommerce/Import/Processors/Term_Import.php(69): BigCommerce\Import\Processors\Category_Import->get_source_data(49) #7 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/src/BigCommerce/Container/Import.php(225): BigCommerce\Import\Processors\Term_Import->run() #8 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/src/BigCommerce/Import/Task_Manager.php(94): BigCommerce\Container\Import->BigCommerce\Container\{closure}('purged_brands') #9 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/src/BigCommerce/Container/Import.php(291): BigCommerce\Import\Task_Manager->run_next('purged_brands') #10 /home/dh_v4jayv/utvaudio.com/wp-includes/class-wp-hook.php(303): BigCommerce\Container\Import->BigCommerce\Container\{closure}('purged_brands') #11 /home/dh_v4jayv/utvaudio.com/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #12 /home/dh_v4jayv/utvaudio.com/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #13 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/src/BigCommerce/Import/Runner/Cron_Runner.php(51): do_action('bigcommerce/imp...', 'purged_brands') #14 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/src/BigCommerce/Container/Import.php(106): BigCommerce\Import\Runner\Cron_Runner->continue_import() #15 /home/dh_v4jayv/utvaudio.com/wp-includes/class-wp-hook.php(301): BigCommerce\Container\Import->BigCommerce\Container\{closure}() #16 /home/dh_v4jayv/utvaudio.com/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array) #17 /home/dh_v4jayv/utvaudio.com/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #18 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/src/BigCommerce/Import/Runner/Cron_Runner.php(73): do_action('bigcommerce_con...') #19 /home/dh_v4jayv/utvaudio.com/wp-content/plugins/bigcommerce/src/BigCommerce/Container/Import.php(110): BigCommerce\Import\Runner\Cron_Runner->ajax_continue_import() #20 /home/dh_v4jayv/utvaudio.com/wp-includes/class-wp-hook.php(301): BigCommerce\Container\Import->BigCommerce\Container\{closure}() #21 /home/dh_v4jayv/utvaudio.com/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #22 /home/dh_v4jayv/utvaudio.com/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #23 /home/dh_v4jayv/utvaudio.com/wp-admin/admin-ajax.php(187): do_action('wp_ajax_bigcomm...') #24 {main} [] []`

However, I've checked all category/sub-category and none come close to this threshold. Additionally, the referenced "category $name" does not exist. 
"...BigCommerce\Api\v3\Model\Category->setName('Chevrolet and G...')" - there is not a category name value that contains the string "Chevrolet and G"

**Comment by tyla-taylor** [comment]
@MoosMase could we get access to the site to debug the import process? At the moment, we aren't able replicate the issue. It appears that something happened during the import and for some reason the category is trying to use the product name instead of its own name. This happened during category data retrieve and that step is running earlier then product fetch (unless the order was changed via hook/filter). Thanks.
